dataset1<-read.csv("general_data.csv")
attach(dataset1)
head(dataset1)
mytable<-table(Attrition)
mytable
pct<-round(mytable/sum(mytable)*100)
pct
labels<-paste(rownames(mytable),"-",pct,"%")
labels
pie(mytable,labels,main="Attrition",col=rainbow(length(labels)))
mytable<-table(Gender)
mytable
pct<-round(mytable/sum(mytable)*100)
pct
labels1<-paste(rownames(mytable),"-",pct,"%")
labels1
pie(mytable,labels1,main="Gender",col=rainbow(length(labels1)))
mytable<-table(Department)
mytable
pct<-round(mytable/sum(mytable)*100)                                          
pct
labels2<-paste(rownames(mytable),"-",pct,"%")
labels2
pie(mytable,labels2,main="Department",col=rainbow(length(labels2)))
wilcox.test(MonthlyIncome~Attrition)
wilcox.test(DistanceFromHome~Attrition)

