install.packages("xlsx")
library("xlsx")
dataset<-read.xlsx("1 Wilcoxon.xlsx",sheetIndex=1)
attach(dataset)
head(dataset)
wilcox.test(TOTALCIN,TOTALCW2,paired=TRUE)
myvariable<-data.frame(TOTALCIN,TOTALCW2,TOTALCW4)
friedman<-as.matrix(myvariable)
friedman.test(friedman)
dataset1<-read.xlsx("3 Mann Whitney.xlsx",sheetIndex=1)
attach(dataset1)
head(dataset1)
wilcox.test(Sales~Design)
dataset2<-read.xlsx("4 Kruskal Wallis.xlsx",sheetIndex=1)
attach(dataset2)
head(dataset2)
kruskal.test(Sales~Design)
dataset3<-read.xlsx("5 Chi square Test.xlsx",sheetIndex=1)
attach(dataset3)
head(dataset3)
chitable<-table(Gender,Smoking)
chitable
print(chisq.test(chitable))
dataset4<-read.xlsx("1. One Sample.xlsx",sheetIndex=1)
attach(dataset4)
head(dataset4)
t.test(Height,mu=65)
dataset5<-read.xlsx("2. Paired Sample.xlsx",sheetIndex=1)
attach(dataset5)
head(dataset5)
t.test(English,Math,paired=TRUE)
dataset6<-read.xlsx("3. Independent Sample.xlsx",sheetIndex=4)
attach(dataset6)
head(dataset6)
t.test(Nonathelete,Athelete,paired=FALSE)
dataset7<-read.xlsx("Correlation.xlsx",sheetIndex=2)
attach(dataset7)
head(dataset7)
dataset8<-read.xlsx("2 Logistic Regression.xlsx",sheetIndex=1)
attach(dataset8)
head(dataset8)
Simple<-lm(Attitude~Duration)
summary(Simple)
Multiple<-lm(Attitude~Duration+Importance)
summary(Multiple)
logistic<-glm(Admit~GRE+GPA+Rank)
summary(logistic)
dataset9<-read.xlsx("2.ANCOVA.xlsx",sheetIndex=1)
attach(dataset9)
head(dataset9)
oneway<-aov(Sales~InStorePromotion)
summary(oneway)
twoway<-aov(Sales~InStorePromotion+Coupon)
summary(twoway)
ancova<-aov(Sales~InStorePromotion+Coupon+ClietelRatings)
summary(ancova)
